config/routes.rb
CardWall::Application.routes.draw do
  resources :walls do
    resources :cards, :only => [:create]
  end
  root :to => 'welcome#show'
end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :prototype
  
  %w[text].each do |attr|
    define_method(attr) do
      val = read_attribute(attr)
      if val.nil?
        prototype.send(attr)
      else
        val
      end
    end
  end

  %w[w h bg_color shadow].each do |attr|
    define_method(attr) do
      val = read_attribute(attr)
      if val.blank?
        prototype.send(attr)
      else
        val
      end
    end
  end
end

app/models/prototype.rb
class Prototype < ActiveRecord::Base
end

app/models/user.rb
require 'ostruct'

class User
  delegate :email_address, to: '@opts'

  def initialize(opts = nil)
    @opts = OpenStruct.new(opts || {})
  end

  def persisted?
    false
  end
end

app/models/wall.rb
class Wall < ActiveRecord::Base
  has_many :cards
  has_many :prototypes
  accepts_nested_attributes_for :cards
  accepts_nested_attributes_for :prototypes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :load_user
  
  private

  def load_user
    @user = session[:user] || User.new
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
end

app/controllers/walls_controller.rb
class WallsController < ApplicationController
  before_filter 'load_wall', only: %w[show update]

  def show
  end

  def update
    if @wall.update_attributes(params[:wall])
      redirect_to @wall, notice: 'Wall updated'
    else
      render 'show'
    end
  end

  private

  def load_wall
    @wall = Wall.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def show
    redirect_to Wall.first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
  def card_style(card)
    format('top: %dpx; left: %dpx; z-index: %d', card.y, card.x, card.z)
  end

  def card_content_style(card)
    format('background-color: %s; width: %dpx; min-height: %dpx', card.bg_color, card.w, card.h)
  end

  def card_classes(card)
    card.shadow ? 'shadow' : nil
  end
end

app/helpers/walls_helper.rb
module WallsHelper
end

app/views/cards/_item.html.haml
= div_for(card, style: card_style(card), class: card_classes(card)) do
  .content{style: "background-color: #{card.bg_color}; width: #{card.w}px; height: #{card.h}px"}
    .text<
      :preserve
        #{h(card.text)}
  .edit_card_form{id: dom_id(card, 'edit')}
    = form.fields_for :cards, card do |f|
      .field.x
        = f.label :x
        = f.text_field :x, class: 'x_input'
      .field.y
        = f.label :y
        = f.text_field :y, class: 'y_input'
      .field.z
        = f.label :z
        = f.text_field :z, class: 'z_input'
      .field.w
        = f.label :w
        = f.text_field :w, class: 'w_input'
      .field.h
        = f.label :h
        = f.text_field :h, class: 'h_input'
      .field.text
        = f.label :text
        = f.text_area :text, rows: 5, class: 'text_input'
      .field.author
        = f.label :author
        = f.text_field :author
      .field.bg_color
        = f.label :bg_color, 'Background'
        = f.text_field :bg_color, class: 'bg_color_input'
      .field.shadow
        = f.label :shadow
        = f.check_box :shadow, class: 'shadow_input'

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Card Wall
    = stylesheet_link_tag :application
    -#= include_stylesheets :screen, media: 'all'
    = csrf_meta_tag
  %body
    %header
      .title
        %h1= link_to 'Card Wall', root_url

    %article
      = yield

    %footer

    = javascript_include_tag :application
    -#= include_javascripts :screen
    = yield :javascript

app/views/walls/_card.html.haml
= div_for(card, style: card_style(card), class: :editable) do
  .content{style: card_content_style(card), class: card_classes(card)}
    .text<
      :preserve
        #{h(card.text)}
  .edit_card_form{id: dom_id(card, 'edit')}
    = form.fields_for :cards, card do |f|
      .field.x
        = f.label :x
        = f.text_field :x, class: 'x_input'
      .field.y
        = f.label :y
        = f.text_field :y, class: 'y_input'
      .field.z
        = f.label :z
        = f.text_field :z, class: 'z_input'
      .field.w
        = f.label :w
        = f.text_field :w, class: 'w_input'
      .field.h
        = f.label :h
        = f.text_field :h, class: 'h_input'
      .field.text
        = f.label :text
        = f.text_area :text, rows: 5, class: 'text_input'
      .field.author
        = f.label :author
        = f.text_field :author
      .field.bg_color
        = f.label :bg_color, 'Background'
        = f.text_field :bg_color, class: 'bg_color_input'
      .field.shadow
        = f.label :shadow
        = f.check_box :shadow, class: 'shadow_input'
    %fieldset
      %legend Actions
      %button Delete
    .instructions
      %p esc = close

app/views/walls/_prototype.html.haml
= div_for(prototype, title: prototype.name, class: :editable, data: {create_url: wall_url(wall)}) do
  .content{style: card_content_style(prototype), class: card_classes(prototype)}
    .text<
      :preserve
        #{h(prototype.text)}
  .new_card_form
    -# form_for :wall_card, wall.cards.build do |f|
      = f.hidden_field :x, value: nil, class: 'x_input'
      = f.hidden_field :y, value: nil, class: 'y_input'
      = f.hidden_field :w, value: prototype.w
      = f.hidden_field :h, value: prototype.h
      = f.hidden_field :text, rows: 5, value: prototype.text
      = f.hidden_field :author, value: prototype.author
      = f.hidden_field :bg_color, value: prototype.bg_color
      = f.check_box :shadow, checked: prototype.shadow
  .edit_card_form{id: dom_id(prototype, 'edit')}
    = form.fields_for :prototypes, prototype do |f|
      .field.w
        = f.label :w
        = f.text_field :w, class: 'w_input'
      .field.h
        = f.label :h
        = f.text_field :h, class: 'h_input'
      .field.text
        = f.label :text
        = f.text_area :text, rows: 5, class: 'text_input'
      .field.author
        = f.label :author
        = f.text_field :author
      .field.bg_color
        = f.label :bg_color, 'Background'
        = f.text_field :bg_color, class: 'bg_color_input'
      .field.shadow
        = f.label :shadow
        = f.check_box :shadow, class: 'shadow_input'
    .instructions
      %p esc = close
  .name
    = prototype.name

app/views/walls/show.html.haml
= form_for @wall do |form|
  %section.dashboard
    .save_button
      = form.submit 'Save (Ctrl-S)', disabled: true
    .flash
      .notice
        - if flash.notice
          %p= notice
      .alert
        - if flash.alert
          %p= alert

    .credits
      %p
        #{link_to 'gregory mcintyre', 'http://gregorymcintyre.com'} with <tt>&lt;3</tt>
      %p
        please #{link_to 'report', 'https://github.com/puyo/cardwall/issues/new'} any problems

    .prototypes
      = render partial: 'prototype', collection: @wall.prototypes, as: :prototype, locals: { form: form, wall: @wall }

  %section.wall#wall
    = render partial: 'card', collection: @wall.cards, as: :card, locals: { form: form }

- content_for :javascript do
  :javascript
    $(function(){
      var dragging = false;

      function bringToTop(elem, others){
        // stolen from jquery.ui.draggable's stack functionality
        var group = $.makeArray(others).sort(function(a,b){
          return (parseInt($(a).css("zIndex"),10) || 0) - (parseInt($(b).css("zIndex"),10) || 0);
        });
        if (!group.length) { return; }
        var min = parseInt(group[0].style.zIndex) || 0;
        $(group).each(function(i){ this.style.zIndex = min + i; });
        elem[0].style.zIndex = min + group.length;
      }

      function setEditPosition(editable){
        editable.find('.edit_card_form').css('left', editable.find('.content').width() + 5);
      }

      $('.editable').click(function() {
        if (dragging === false) {
          var editable = $(this).closest('.editable');
          var selected = editable.hasClass('selected');
          bringToTop(editable, $('.editable'));
          $('.editable').removeClass('selected');
          if (!selected) {
            editable.addClass('selected');
            editable.find('input:visible, textarea:visible').first().focus();
            setEditPosition(editable);
          }
        } else {
          dragging = false;
        }
      });

      $('.editable').change(function(){
        $(this).addClass('changed');
        $('#wall_submit').addClass('changed').attr('disabled', false);
      });

      $('.card').draggable({
        containment: "#wall",
        disabled: false,
        stack: '.card',
        start: function() { dragging = true; },
        stop: function(event, ui) {
          var pos = $(this).position();
          $(this).find('.x_input').val(pos.left);
          $(this).find('.y_input').val(pos.top);
          $('.card').each(function(){
            $(this).find('.z_input').val($(this).css('z-index'));
          });
          $(this).trigger('change');
        }
      });

      $('.text_input').bind('keydown keyup keypress', function(){
        var editable = $(this).closest('.editable');
        var text = editable.find('.content .text');
        if ($(this).val() !== text.text()) {
          $(this).trigger('change');
        }
        editable.find('.content .text').text($(this).val());
      });

      $('.w_input').change(function(){
        var editable = $(this).closest('.editable');
        editable.find('.content').css('width', $(this).val());
        setEditPosition(editable);
      });
      $('.h_input').change(function(){ $(this).closest('editable').find('.content').css('min-height', $(this).val() + 'px'); });

      $('.shadow_input').change(function(){
        var content = $(this).closest('.editable').find('.content');
        if ($(this).attr('checked')) {
          content.addClass('shadow');
        } else {
          content.removeClass('shadow');
        }
      });

      $('.bg_color_input').bind('keydown keyup keypress', function(){
        $(this).closest('.editable').find('.content').css('background-color', $(this).val());
        $(this).trigger('change');
      });

      $('.prototype').sortable({
        disabled: false,
        stop: function(event, ui) {
          var form = ui.find('form');
          form.find()
          //console.log(event, ui);
        }
      });

      $(document).keyup(function(event){
        if (event.keyCode === 27) {
          $('.selected').removeClass('selected');
        }
      });

      $(document).keypress(function(event){
        if (event.charCode === 19 && event.ctrlKey && $('#wall_submit').hasClass('changed')) {
          $('##{dom_id(@wall, 'edit')}').submit();
        }
      });

      $('.flash').find('.notice, .alert').find('p').delay(5000).fadeOut('slow');
    });

app/views/welcome/show.html.haml
%section.wall
  .buttons
    //%button.button.mode_button{value: 'view'} View
    //%button.button.mode_button{value: 'move'} Move
    //%button.button.mode_button{value: 'edit'} Edit
    %button.button.save_button{:disabled => true} Save

  #mode.view
    #wall
      - @wall.cards.each do |card|
        = div_for(card, 'data-wall-id' => @wall.id, 'data-card-id' => card.id, style: "background-color: #{card.bg_color}; top: #{card.y}px; left: #{card.x}px; width: #{card.w}px; height: #{card.h}px; z-index: #{card.z}") do
          =h card.content

- content_for :javascript do
  :javascript
    $(function() {
      function cards() {
        return $("#wall").find('.card');
      }

      function setMode(mode) {
        $('#mode').attr('class', mode);
      }

      function setModified() {
        $('.save_button').removeAttr('disabled');
      }

      cards().draggable({
        containment: "#wall",
        disabled: false,
        stop: function(event, ui) { setModified(); }
      }).each(function(){
        $(this).fancybox({
          type: 'ajax',
          ajax: {
            url: '/walls/' + $(this).attr('data-wall-id') + '/cards/' + $(this).attr('data-card-id') + '/edit'
          }
        });
      });

      // mode switching
      $('.mode_button').click(function(){
        setMode($(this).attr('value'));
      });

      $('#wall').find('.card').click(function(){
        //alert('click');
        //$(this).html('<input type="textarea">');
      });
    });